FORMAT: 1A
HOST: https://sembako.bandung.go.id/api

# Bandung Market Monitor Web API

Bandung Market Monitor Web API is an API allowing consumers to retrieve monitoring data.

## Monitor Collection [/monitors]

### List Monitors [GET]

TBD


## Market Collection [/markets]

### List Markets [GET]

TBD

### Create Market [POST]

TBD